### ISSUE TITLE
Error: Out of memory while extracting big file

### ISSUE THREAD

**Issue by borodin-devel** [Aldrin-John-Olaer-Manalansan/RA2YR-reMIXer#4]
Encountered Error: Out of memory during extracting big MIX file. Recoverable for both header and LMD. Recommended method is used. Hardly believe that I am out of RAM - have 32 GB of hardware.

▶	714: reMIX_FileObj.Size := reMIX_Area_Info_Offset + reMIX_Area_Info_Size + reMIX_Area_Body_Size

Call stack:
*#1 (714) : [Buffer.Prototype.Size.Set] reMIX_FileObj.Size := reMIX_Area_Info_Offset + reMIX_Area_Info_Size + reMIX_Area_Body_Size
*#1 (714) : [reMIX_Level_3] reMIX_FileObj.Size := reMIX_Area_Info_Offset + reMIX_Area_Info_Size + reMIX_Area_Body_Size
*#1 (327) : [Gui_ControlPanel_reMIXAllTargets_DoWork] reMIX_Level_%Gui_ControlPanel_DDL.Value%(Gui_ControlPanel_LV.GetText(A_Index,3))
> Gui

File will be attached in G-Disk.

**Comment by Aldrin-John-Olaer-Manalansan** [comment]
This ticket is now marked for UAT for 1 week. Test the latest build and report here if a problem connected to this ticket have been encountered.

**Comment by Aldrin-John-Olaer-Manalansan** [comment]
This issue is now assumed as Fixed.

Ticket Closed.
